import 'package:flutter/material.dart';
import 'dart:math';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Gardirop Test',
      home: Scaffold(
        appBar: AppBar(title: Text('Gardirop Test')),
        body: TestScreen(),
      ),
    );
  }
}

class TestScreen extends StatefulWidget {
  @override
  _TestScreenState createState() => _TestScreenState();
}

class _TestScreenState extends State<TestScreen> {
  // 20 örnek erkek kıyafet resmi URL’si
  List<String> images = [
    'https://raw.githubusercontent.com/kullaniciadi/gardrop-test-assets/main/shirt1.png',
    'https://raw.githubusercontent.com/kullaniciadi/gardrop-test-assets/main/shirt2.png',
    'https://raw.githubusercontent.com/kullaniciadi/gardrop-test-assets/main/shirt3.png',
    'https://raw.githubusercontent.com/kullaniciadi/gardrop-test-assets/main/shirt4.png',
    'https://raw.githubusercontent.com/kullaniciadi/gardrop-test-assets/main/shirt5.png',
    'https://raw.githubusercontent.com/kullaniciadi/gardrop-test-assets/main/shirt6.png',
    'https://raw.githubusercontent.com/kullaniciadi/gardrop-test-assets/main/shirt7.png',
    'https://raw.githubusercontent.com/kullaniciadi/gardrop-test-assets/main/shirt8.png',
    'https://raw.githubusercontent.com/kullaniciadi/gardrop-test-assets/main/shirt9.png',
    'https://raw.githubusercontent.com/kullaniciadi/gardrop-test-assets/main/shirt10.png',
    'https://raw.githubusercontent.com/kullaniciadi/gardrop-test-assets/main/pants1.png',
    'https://raw.githubusercontent.com/kullaniciadi/gardrop-test-assets/main/pants2.png',
    'https://raw.githubusercontent.com/kullaniciadi/gardrop-test-assets/main/pants3.png',
    'https://raw.githubusercontent.com/kullaniciadi/gardrop-test-assets/main/pants4.png',
    'https://raw.githubusercontent.com/kullaniciadi/gardrop-test-assets/main/pants5.png',
    'https://raw.githubusercontent.com/kullaniciadi/gardrop-test-assets/main/jacket1.png',
    'https://raw.githubusercontent.com/kullaniciadi/gardrop-test-assets/main/jacket2.png',
    'https://raw.githubusercontent.com/kullaniciadi/gardrop-test-assets/main/shoes1.png',
    'https://raw.githubusercontent.com/kullaniciadi/gardrop-test-assets/main/shoes2.png',
    'https://raw.githubusercontent.com/kullaniciadi/gardrop-test-assets/main/shoes3.png',
  ];

  String currentImage = '';

  @override
  void initState() {
    super.initState();
    // Uygulama ilk açıldığında rastgele bir resim göster
    currentImage = images[Random().nextInt(images.length)];
  }

  void showRandomImage() {
    setState(() {
      currentImage = images[Random().nextInt(images.length)];
    });
  }

  @override
  Widget build(BuildContext context) {
    return Center(
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          Image.network(currentImage, height: 250),
          SizedBox(height: 20),
          ElevatedButton(
            onPressed: showRandomImage,
            child: Text('Rastgele Kombin Göster'),
          ),
        ],
      ),
    );
  }
}
